"use strict";(()=>{function m(t){return new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(t)}function v(t){return t<6e4?`${Math.round(t/1e3)}s`:`${Math.round(t/6e4)}m`}function p(t){if(!t)return"No activity yet";let e=Math.floor((Date.now()-t)/1e3);if(e<60)return`${e}s ago`;let n=Math.floor(e/60);return n<60?`${n}m ago`:`${Math.floor(n/60)}h ago`}var a=__SIDEBAR_INIT__.lastActivityMs;function E(t,e){let n=document.getElementById("statusDot"),o=document.getElementById("statusText"),s=document.getElementById("statusLabel");!n||!o||!s||(e&&(a=e),t?(n.className="status-dot active",o.textContent="Active",o.style.color="var(--vscode-foreground)",s.textContent=""):(n.className="status-dot idle",o.textContent="Idle",o.style.color="var(--vscode-descriptionForeground)",s.textContent=a?p(a):"No activity yet"))}setInterval(()=>{if(document.getElementById("statusDot")?.classList.contains("idle")&&a){let e=document.getElementById("statusLabel");e&&(e.textContent=p(a))}},1e4);function b(t){return t==="claude_code"?"#FFB085":t==="codex"?"#F0FF42":t==="copilot"?"#00EAFF":"#90a4ae"}function C(t){return t==="claude_code"?"Claude":t==="codex"?"Codex":"Copilot"}function f(t){let e=document.getElementById("agentKey");if(e){if(!t.length){e.innerHTML="";return}e.innerHTML=`<div style="display:flex;gap:10px;font-size:10px;color:var(--vscode-descriptionForeground);align-items:center;flex-wrap:wrap">${t.map(n=>`<span style="display:flex;align-items:center;gap:4px"><span style="display:inline-block;width:7px;height:7px;border-radius:50%;background:${b(n)}"></span>${C(n)}</span>`).join("")}</div>`}}function y(t){let e=document.getElementById("latestSessionCard"),n=document.getElementById("latestSessionBody");if(!e||!n)return;if(!t){e.style.display="none";return}e.style.display="";let o=t.source==="claude_code"?"Claude":t.source==="codex"?"Codex":"Copilot",s=t.errors>0?`<span style="color:var(--vscode-testing-iconFailed,#f44)">${t.errors} err</span>`:"";n.innerHTML=`
    <div style="display:flex;justify-content:space-between;align-items:baseline;margin-bottom:3px">
      <span style="color:var(--vscode-descriptionForeground)">${o}</span>
      <span style="color:var(--vscode-descriptionForeground)">${v(t.durationMs)}</span>
    </div>
    <div style="color:var(--vscode-textLink-foreground);margin-bottom:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${t.model||"\u2014"}</div>
    <div style="display:flex;gap:12px;font-size:10px;color:var(--vscode-descriptionForeground)">
      <span>${t.totalLlmCalls} turn${t.totalLlmCalls!==1?"s":""}</span>
      <span>${t.totalToolCalls} tool${t.totalToolCalls!==1?"s":""}</span>
      ${s}
      <span>${Math.round(t.cacheHitRate*100)}% cache</span>
    </div>`}var i=__SIDEBAR_INIT__.agentSources;f(i);y(__SIDEBAR_INIT__.latestSession);var r=acquireVsCodeApi();document.getElementById("sessionLimitSelect")?.addEventListener("change",function(){r.postMessage({type:"setSessionLimit",value:this.value})});document.getElementById("agentFilterSelect")?.addEventListener("change",function(){r.postMessage({type:"setAgentFilter",value:this.value})});document.getElementById("clearBtn")?.addEventListener("click",()=>{r.postMessage({type:"clearAll"})});window.addEventListener("message",t=>{let e=t.data;if(e.type==="update"){let n=document.getElementById("sessionCountLabel");n&&(n.textContent=String(e.sessionCount??0));let o=document.getElementById("outputTokens"),s=document.getElementById("inputTokens"),c=document.getElementById("cacheHitRate"),u=document.getElementById("avgTurns"),l=document.getElementById("totalErrors"),d=document.getElementById("totalToolCalls");if(o&&(o.textContent=m(e.totalOutputTokens??0)),s&&(s.textContent=m(e.totalInputTokens??0)),c&&(c.textContent=`${e.cacheHitPct??0}%`),u&&(u.textContent=String(e.avgTurns??0)),l){let g=e.totalErrors??0;l.textContent=String(g),l.style.color=g>0?"var(--vscode-testing-iconFailed,#f44)":""}d&&(d.textContent=String(e.totalToolCalls??0)),E(e.isActive??!1,e.lastActivityMs),e.agentSources&&(i=e.agentSources,f(i)),"latestSession"in e&&y(e.latestSession??null)}else if(e.type==="agentFilterChanged"){let n=document.getElementById("agentFilterSelect");n&&e.value&&(n.value=e.value)}});})();
